version: '3.6'

volumes:
  pointrq13: { }

services:
  postgres:
    image: postgres:13.5-alpine3.15
    container_name: pg-pointrq
    volumes:
      - pointrq13:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pointr
      POSTGRES_PASSWORD: pointr
    ports:
      - 5435:5432